### ISSUE TITLE
Debugging Initial PKT file

### ISSUE THREAD

**Issue by JanssensBart** [JanssensBart/TopDesignE#3]
Search for bugs in the iniatial files

## Tasks:

- [x] checked physical layer (cables)
- [ ] checked management VLAN
- [ ] checked SSH on all switches
- [x] checked IP & VLAN
- [x] checked VTP server & client
